package org.wcci.apimastery;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import org.wcci.apimastery.Entities.Album;
import org.wcci.apimastery.Entities.Artist;
import org.wcci.apimastery.Entities.Song;
import org.wcci.apimastery.Storage.Repositories.AlbumRepository;
import org.wcci.apimastery.Storage.Repositories.ArtistRepository;
import org.wcci.apimastery.Storage.Repositories.SongRepository;

@Component
public class Populator implements CommandLineRunner {

   @Autowired
   private ArtistRepository artistRepository;
   @Autowired
   private AlbumRepository albumRepository;
   @Autowired
   private SongRepository songRepository;


    @Override
    public void run(String... args) throws Exception {
        Artist rollinsBand = new Artist("Rollins Band");
        artistRepository.save(rollinsBand);
        Artist porridgeRadio = new Artist("Porridge Radio");
        artistRepository.save(porridgeRadio);
        Artist drake = new Artist("Drake");
        artistRepository.save(drake);
        Artist slightlyStoopid = new Artist("Slightly Stoopid");
        artistRepository.save(slightlyStoopid);
        Artist sufjanStevens = new Artist("Sufjan Stevens");
        artistRepository.save(sufjanStevens);
        Artist weirdAlYankovic = new Artist("Weird Al Yankovic");
        artistRepository.save(weirdAlYankovic);

        Album theEndOfSilence = new Album("The End Of Silence", rollinsBand, "https://upload.wikimedia.org/wikipedia/en/b/b5/Rollins_Band_-_The_End_of_Silence.jpg");
        albumRepository.save(theEndOfSilence);
        Album aNicerShadeOfRed = new Album("A Nicer Shade Of Red", rollinsBand, "https://upload.wikimedia.org/wikipedia/en/f/fb/Rollins_Red.jpg");
        albumRepository.save(aNicerShadeOfRed);
        Album ricePasta = new Album("Rice, Pasta, and Other Fillers", porridgeRadio, "https://img.discogs.com/A9FXqoR8Vd3bqbj1O4TYtQUPwEE=/fit-in/500x784/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-8852963-1476134606-9183.jpeg.jpg");
        albumRepository.save(ricePasta);
        Album everyBad = new Album("Every Bad", porridgeRadio, "https://media.pitchfork.com/photos/5e61297a5580e10008f9f3b2/1:1/w_320/EveryBad.jpg");
        albumRepository.save(everyBad);
        Album nothingSame = new Album("Nothing Was The Same", drake, "https://catalog.1234gorecords.com/images/R-5191591-1387027368-6374.jpeg.jpg");
        albumRepository.save(nothingSame);
        Album views = new Album("Views", drake, "https://upload.wikimedia.org/wikipedia/en/thumb/a/af/Drake_-_Views_cover.jpg/220px-Drake_-_Views_cover.jpg");
        albumRepository.save(views);
        Album closerToSun = new Album("Closer To The Sun", slightlyStoopid, "https://upload.wikimedia.org/wikipedia/en/5/5c/Closertothesun.jpg");
        albumRepository.save(closerToSun);
        Album everythingNeed = new Album("Everything You Need", slightlyStoopid, "https://upload.wikimedia.org/wikipedia/en/thumb/e/e4/Everythingyouneedss.jpg/220px-Everythingyouneedss.jpg");
        albumRepository.save(everythingNeed);
        Album ageAdz = new Album("The Age Of Adz", sufjanStevens, "https://upload.wikimedia.org/wikipedia/en/e/e9/Sufjanstevensageofadz.jpg");
        albumRepository.save(ageAdz);
        Album carrieLowell = new Album("Carrie & Lowell", sufjanStevens, "https://upload.wikimedia.org/wikipedia/en/e/ec/Sufjan_Stevens_-_Carrie_%26_Lowell.jpg");
        albumRepository.save(carrieLowell);
        Album badHair = new Album("Bad Hair Day", weirdAlYankovic, "https://upload.wikimedia.org/wikipedia/en/4/49/BadHairDayCover.jpg");
        albumRepository.save(badHair);
        Album runningScissors = new Album("Running With Scissors", weirdAlYankovic, "https://upload.wikimedia.org/wikipedia/en/b/b3/Running_with_Scissors_%28Weird_Al_Yankovic_album_-_cover_art%29.jpg");
        albumRepository.save(runningScissors);

        Song lowSelfOpinion = new Song ("Low Self Opinion", "5:18", theEndOfSilence);
        songRepository.save(lowSelfOpinion);
        Song grip = new Song ("Grip", "4:50", theEndOfSilence);
        songRepository.save(grip);
        Song tearing = new Song("Tearing", "4:58", theEndOfSilence);
        songRepository.save(tearing);
        Song youDidntNeed = new Song ("You Didn't Need", "5:30", theEndOfSilence);
        songRepository.save(youDidntNeed);
        Song almostReal = new Song ("Almost Real", "8:03", theEndOfSilence);
        songRepository.save(almostReal);
        Song obscene = new Song ("Obscene", "8:50", theEndOfSilence);
        songRepository.save(obscene);
        Song whatDoYouDo = new Song ("What Do You Do", "7:22", theEndOfSilence);
        songRepository.save(whatDoYouDo);
        Song bluesJam = new Song("Blues Jam", "11:46", theEndOfSilence);
        songRepository.save(bluesJam);
        Song anotherLife = new Song("Another Life", "4:39", theEndOfSilence);
        songRepository.save(anotherLife);
        Song justLikeYou = new Song("Just Like You", "9:30", theEndOfSilence);
        songRepository.save(justLikeYou);

        Song tooMuchRock = new Song("Too Much Rock and Roll", "3:50", aNicerShadeOfRed);
        songRepository.save(tooMuchRock);
        Song marcus = new Song("Marcus Has the Evil in Him", "4:01", aNicerShadeOfRed);
        songRepository.save(marcus);
        Song nowhere = new Song("Nowhere to Go but Inside", "3:04", aNicerShadeOfRed);
        songRepository.save(nowhere);
        Song tenX = new Song("10X", "3:04", aNicerShadeOfRed);
        songRepository.save(tenX);
        Song always = new Song("Always the Same", "2:57", aNicerShadeOfRed);
        songRepository.save(always);
        Song soul = new Song("Soul Implant", "1:56", aNicerShadeOfRed);
        songRepository.save(soul);
        Song fun = new Song("Ain't It Fun", "3:43", aNicerShadeOfRed);
        songRepository.save(fun);
        Song lost = new Song("You Lost Me", "5:47", aNicerShadeOfRed);
        songRepository.save(lost);
        Song stone = new Song("Stone Washed Clean", "4:18", aNicerShadeOfRed);
        songRepository.save(stone);
        Song lifeDenied = new Song("A Life Denied", "3:25", aNicerShadeOfRed);
        songRepository.save(lifeDenied);
        Song number = new Song("Your Number IS One (Long Version)", "4:37", aNicerShadeOfRed);
        songRepository.save(number);
        Song drag = new Song("Such a Drag", "12:55", aNicerShadeOfRed);
        songRepository.save(drag);

        Song danish = new Song("Danish Pastry Lyrics", "3:32", ricePasta);
        songRepository.save(danish);
        Song lemonade = new Song("Lemonade", "2:41", ricePasta);
        songRepository.save(lemonade);
        Song barks = new Song("Barks Like A Dog", "5:26", ricePasta);
        songRepository.save(barks);
        Song cow = new Song("Walking The Cow (Daniel Johnston cover)", "2:35", ricePasta);
        songRepository.save(cow);
        Song hearMe = new Song("Can U Hear Me Now", "7:33", ricePasta);
        songRepository.save(hearMe);
        Song sorry = new Song("Sorry", "5:31", ricePasta);
        songRepository.save(sorry);
        Song worms = new Song("Worms", "1:51", ricePasta);
        songRepository.save(worms);
        Song wasLike = new Song("And I Was Like", "1:38", ricePasta);
        songRepository.save(wasLike);
        Song eugh = new Song("Eugh", "4:38", ricePasta);
        songRepository.save(eugh);

        Song sweet = new Song("Sweet", "3:42", everyBad);
        songRepository.save(sweet);
        Song askMe = new Song("Don't Ask Me Twice", "3:21", everyBad);
        songRepository.save(askMe);
        Song giveTake = new Song("Give/Take", "3:53", everyBad);
        songRepository.save(giveTake);
        Song lilac = new Song("Lilac", "5:27", everyBad);
        songRepository.save(lilac);
        Song circling = new Song("Circling", "3:20", everyBad);
        songRepository.save(circling);

        Song tuscan = new Song("Tuscan Leather", "6:06", nothingSame);
        songRepository.save(tuscan);
        Song furthest = new Song("Furthest Things", "4:27", nothingSame);
        songRepository.save(furthest);
        Song bottom = new Song("Started From the Bottom", "2:53", nothingSame);
        songRepository.save(bottom);
        Song wutang = new Song("Wu-Tang Forever", "3:37", nothingSame);
        songRepository.save(wutang);
        Song ownIt = new Song("Own It", "4:11", nothingSame);
        songRepository.save(ownIt);
        Song worst = new Song("Worst Behavior", "4:30", nothingSame);
        songRepository.save(worst);
        Song time = new Song("From Time feat. Jhene Aiko", "5:22", nothingSame);
        songRepository.save(time);
        Song holdOn = new Song("Hold On, We're Going Home feat. Majid Jordan", "3:51", nothingSame);
        songRepository.save(holdOn);
        Song connect = new Song("Connect", "4:56", nothingSame);
        songRepository.save(connect);
        Song language = new Song("The Language", "3:44", nothingSame);
        songRepository.save(language);
        Song city = new Song("305 to My City feat. Detail", "4:15", nothingSame);
        songRepository.save(city);
        Song tooMuch = new Song("Too Much", "4:21", nothingSame);
        songRepository.save(tooMuch);
        Song pound = new Song("Pound Cake/Paris Morton Music feat. Jay-Z", "27:13", nothingSame);
        songRepository.save(pound);

        Song family = new Song("Keep the Family Close", "5:28", views);
        songRepository.save(family);
        Song nine = new Song("9", "4:15", views);
        songRepository.save(nine);
        Song withMe = new Song("U With Me?", "4:57", views);
        songRepository.save(withMe);
        Song feel = new Song("Feel No Ways", "4:00", views);
        songRepository.save(feel);
        Song hype = new Song("Hype", "3:29", views);
        songRepository.save(hype);
        Song weston = new Song("Weston Road Flows", "4:13", views);
        songRepository.save(weston);
        Song redemption = new Song("Redemption", "5:33", views);
        songRepository.save(redemption);
        Song withYou = new Song("With You feat. PartyNextDoor", "3:15", views);
        songRepository.save(withYou);
        Song faithful = new Song("Faithful feat. Pimp C & dvsn", "4:50", views);
        songRepository.save(faithful);
        Song stillHere = new Song("Still Here", "3:09", views);
        songRepository.save(stillHere);
        Song controlla = new Song("Controlla", "4:05", views);
        songRepository.save(controlla);
        Song oneDance = new Song("One Dance feat Wizkid & Kyle", "2:53", views);
        songRepository.save(oneDance);
        Song child = new Song("Child Play", "3:32", views);
        songRepository.save(child);
        Song pop = new Song("Pop Style", "3:32", views);
        songRepository.save(pop);
        Song tooGood = new Song("Too Good feat. Rihanna", "4:23", views);
        songRepository.save(tooGood);
        Song summer = new Song("Summers Over Interlude", "1:46", views);
        songRepository.save(summer);
        Song fire = new Song("Fire & Desire", "3:58", views);
        songRepository.save(fire);
        Song viewsSong = new Song("Views", "5:11", views);
        songRepository.save(viewsSong);
        Song hotline = new Song("Hotline Bling", "4:27", views);
        songRepository.save(hotline);

        Song intro = new Song("Intro", "1:17", closerToSun);
        songRepository.save(intro);
        Song babylon = new Song("Babylon Is Falling", "2:25", closerToSun);
        songRepository.save(babylon);
        Song somebody = new Song("Somebody", "2:52", closerToSun);
        songRepository.save(somebody);
        Song fat = new Song("Fat Spliffs", "3:07", closerToSun);
        songRepository.save(fat);
        Song bandelero = new Song("Bandelero", "2:47", closerToSun);
        songRepository.save(bandelero);
        Song seeIt = new Song("See It No Other Way feat. Barrington Levy & Mr. Mutton", "3:53", closerToSun);
        songRepository.save(seeIt);
        Song nothin = new Song("Nothin Over Me", "1:20", closerToSun);
        songRepository.save(nothin);
        Song joint = new Song("This Joint", "4:07", closerToSun);
        songRepository.save(joint);
        Song older = new Song("Older", "3:39", closerToSun);
        songRepository.save(older);
        Song money = new Song("Aint Got A Lot Of Money", "2:58", closerToSun);
        songRepository.save(money);
        Song wet = new Song("Til It Gets Wet", "2:37", closerToSun);
        songRepository.save(wet);
        Song care = new Song("Don't Care feat. Bill and Prof. Most", "4:39", closerToSun);
        songRepository.save(care);
        Song basher = new Song("Basher", "2:31", closerToSun);
        songRepository.save(basher);
        Song righteous = new Song("Righteous Man", "2:35", closerToSun);
        songRepository.save(righteous);
        Song plane = new Song("Up On A Plane", "3:00", closerToSun);
        songRepository.save(plane);
        Song waiting = new Song("Waiting", "2:55", closerToSun);
        songRepository.save(waiting);
        Song closerToSunSong = new Song("Closer to the Sun", "2:25", closerToSun);
        songRepository.save(closerToSunSong);
        Song zeplike = new Song("Zeplike", "3:34", closerToSun);
        songRepository.save(zeplike);
        Song dome = new Song("Come for My Dome", "1:29", closerToSun);
        songRepository.save(dome);
        Song road = new Song("Open Road", "6:24", closerToSun);
        songRepository.save(road);

        Song everythingNeedSong = new Song("Everything You Need", "3:33", everythingNeed);
        songRepository.save(everythingNeedSong);
        Song officer = new Song("Officer", "3:52", everythingNeed);
        songRepository.save(officer);
        Song questionable = new Song("Questionable", "2:07", everythingNeed);
        songRepository.save(questionable);
        Song runnin = new Song("Runnin With a Gun", "3:31", everythingNeed);
        songRepository.save(runnin);
        Song killin = new Song("Killin Me Deep Inside", "4:54", everythingNeed);
        songRepository.save(killin);
        Song gentlemen = new Song("Perfect Gentlemen", "1:40", everythingNeed);
        songRepository.save(gentlemen);
        Song wicked = new Song("Wicked Rebel", "4:03", everythingNeed);
        songRepository.save(wicked);
        Song honey = new Song("Sweet Honey", "3:51", everythingNeed);
        songRepository.save(honey);
        Song punkRock = new Song("Punk Rock Billy", "1:38", everythingNeed);
        songRepository.save(punkRock);
        Song worldRound = new Song("World Goes Round", "3:55", everythingNeed);
        songRepository.save(worldRound);
        Song wiseman = new Song("Wiseman", "3:21", everythingNeed);
        songRepository.save(wiseman);
        Song jetPlane = new Song("Leaving on a Jet Plane", "3:16", everythingNeed);
        songRepository.save(jetPlane);
        Song mellow = new Song("Mellow Mood", "4:41", everythingNeed);
        songRepository.save(mellow);
        Song collie = new Song("Collie Man", "2:13", everythingNeed);
        songRepository.save(collie);

        Song futileDevices = new Song("Futile Devices", "2:11", ageAdz);
        songRepository.save(futileDevices);
        Song tooMuchSong = new Song("Too Much", "6:44",  ageAdz);
        songRepository.save(tooMuchSong);
        Song ageOfAdz = new Song("Age Of Adz", "8:00", ageAdz);
        songRepository.save(ageOfAdz);
        Song iWalked = new Song("I Walked", "5:02", ageAdz);
        songRepository.save(iWalked);
        Song imOlder = new Song("Now That I'm Older", "4:56", ageAdz);
        songRepository.save(imOlder);
        Song getRight = new Song("Get Real Get Right", "5:10", ageAdz);
        songRepository.save(getRight);
        Song badCommunication = new Song("Bad Communication", "2:24", ageAdz);
        songRepository.save(badCommunication);
        Song vesuvius = new Song("Vesuvius", "5:26", ageAdz);
        songRepository.save(vesuvius);
        Song forMyself = new Song("All For Myself", "2:55", ageAdz);
        songRepository.save(forMyself);
        Song beWell = new Song("I Want To Be Well", "6:27", ageAdz);
        songRepository.save(beWell);
        Song impossibleSoul = new Song("Impossible Soul", "25:35", ageAdz);
        songRepository.save(impossibleSoul);

        Song withDignity = new Song("Death With Dignity", "4:00", carrieLowell);
        songRepository.save(withDignity);
        Song knownBetter = new Song("Should Have Known Better", "5:08", carrieLowell);
        songRepository.save(knownBetter);
        Song allOfYou = new Song("All Of Me Wnats All Of You", "3:41", carrieLowell);
        songRepository.save(allOfYou);
        Song theBlood = new Song("Drawn To The Blood", "3:18", carrieLowell);
        songRepository.save(theBlood);
        Song eugene = new Song("Eugene", "2:26", carrieLowell);
        songRepository.save(eugene);
        Song ofJuly = new Song("Fourth Of July", "4:40", carrieLowell);
        songRepository.save(ofJuly);
        Song onlyThing = new Song("The Only Thing", "4:44", carrieLowell);
        songRepository.save(onlyThing);
        Song andLowell = new Song("Carrie And Lowell", "3:14", carrieLowell);
        songRepository.save(andLowell);
        Song myBeloved = new Song("John My Beloved", "5:03", carrieLowell);
        songRepository.save(myBeloved);
        Song ofTheCross = new Song("No Shade In The Shadow Of The Cross", "2:40", carrieLowell);
        songRepository.save(ofTheCross);
        Song bucketOfGold = new Song("Blue Bucket Of Gold", "4:44", carrieLowell);
        songRepository.save(bucketOfGold);

        Song amishParadise = new Song("Amish Paradise", "3:20", badHair);
        songRepository.save(amishParadise);
        Song knowIsWrong = new Song("Everything You Know Is Wrong", "3:48", badHair);
        songRepository.save(knowIsWrong);
        Song cavitySearch = new Song("Cavity Search", "4:19", badHair);
        songRepository.save(cavitySearch);
        Song inSick = new Song("Callin' In Sick", "3:40", badHair);
        songRepository.save(inSick);
        Song altPolka = new Song("Alternative Polka", "4:50", badHair);
        songRepository.save(altPolka);
        Song beenGone = new Song("Since You've Been Gone", "1:20", badHair);
        songRepository.save(beenGone);
        Song gump = new Song("Gump", "2:11", badHair);
        songRepository.save(gump);
        Song sickOfYou = new Song("I'm So Sick Of You", "3:26", badHair);
        songRepository.save(sickOfYou);
        Song syndicated = new Song("Syndicated Inc", "3:54", badHair);
        songRepository.save(syndicated);
        Song rememberLarry = new Song("I Remember Larry", "3:56", badHair);
        songRepository.save(rememberLarry);
        Song phoneCalls = new Song("Phone Calls", "3:22", badHair);
        songRepository.save(phoneCalls);
        Song wentCrazy = new Song("The Night Santa Went Crazy", "4:03", badHair);
        songRepository.save(wentCrazy);

        Song sagaBegins = new Song("The Saga Begins", "5:27", runningScissors);
        songRepository.save(sagaBegins);
        Song eddieVedder = new Song("My Baby's In Love With Eddie Vedder", "3:25", runningScissors);
        songRepository.save(eddieVedder);
        Song flyRabbi = new Song("Pretty Fly For A Rabbi", "3:02", runningScissors);
        songRepository.save(flyRabbi);
        Song showTheme = new Song("The Weird Al Show Theme", "1:14", runningScissors);
        songRepository.save(showTheme);
        Song jerrySpringer = new Song("Jerry Springer", "2:46", runningScissors);
        songRepository.save(jerrySpringer);
        Song germs = new Song("Germs", "4:38", runningScissors);
        songRepository.save(germs);
        Song polkaPower = new Song("Polka Power", "4:21", runningScissors);
        songRepository.save(polkaPower);
        Song forToday = new Song("Your Horoscope For Today", "3:59", runningScissors);
        songRepository.save(forToday);
        Song thePentiums = new Song("It's All About The Pentiums", "3:34", runningScissors);
        songRepository.save(thePentiums);
        Song truckSong = new Song("Truck Drivin' Song", "2:27", runningScissors);
        songRepository.save(truckSong);
        Song diet = new Song("Grapefruit Diet", "3:30", runningScissors);
        songRepository.save(diet);
        Song albuquerque = new Song("Albuquerque", "11:23", runningScissors);
        songRepository.save(albuquerque);

    }
}
