package org.wcci.apimastery;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

@Component
public class Populator implements CommandLineRunner {

   @Autowired
   private ArtistRepository artistRepository;
   @Autowired
   private AlbumRepository albumRepository;
   @Autowired
   private SongRepository songRepository;


    @Override
    public void run(String... args) throws Exception {
        Artist rollinsBand = new Artist("Rollins Band");
        artistRepository.save(rollinsBand);
        Artist porridgeRadio = new Artist("Porridge Radio");
        artistRepository.save(porridgeRadio);
        Artist drake = new Artist("Drake");
        artistRepository.save(drake);
        Artist slightlyStoopid = new Artist("Slightly Stoopid");
        artistRepository.save(slightlyStoopid);
        Artist sufjanStevens = new Artist("Sufjan Stevens");
        artistRepository.save(sufjanStevens);
        Artist weirdAlYankovic = new Artist("Weird Al Yankovic");
        artistRepository.save(weirdAlYankovic);

        Album theEndOfSilence = new Album("The End Of Silence", rollinsBand);
        albumRepository.save(theEndOfSilence);
        Album aNicerShadeOfRed = new Album("A Nicer Shade Of Red", rollinsBand);
        albumRepository.save(aNicerShadeOfRed);
        Album ricePasta = new Album("Rice, Pasta, and Other Fillers", porridgeRadio);
        albumRepository.save(ricePasta);
        Album everyBad = new Album("Every Bad", porridgeRadio);
        albumRepository.save(everyBad);
        Album nothingSame = new Album("Nothing Was The Same", drake);
        albumRepository.save(nothingSame);
        Album views = new Album("Views", drake);
        albumRepository.save(views);
        Album closerToSun = new Album("Closer To The Sun", slightlyStoopid);
        albumRepository.save(closerToSun);
        Album everythingNeed = new Album("Everything You Need", slightlyStoopid);
        albumRepository.save(everythingNeed);
        Album ageAdz = new Album("The Age Of Adz", sufjanStevens);
        albumRepository.save(ageAdz);
        Album carrieLowell = new Album("Carrie & Lowell", sufjanStevens);
        albumRepository.save(carrieLowell);
        Album badHair = new Album("Bad Hair Day", weirdAlYankovic);
        albumRepository.save(badHair);
        Album runningScissors = new Album("Running With Scissors", weirdAlYankovic);
        albumRepository.save(runningScissors);

        Song lowSelfOpinion = new Song ("Low Self Opinion", "5:18", rollinsBand, theEndOfSilence);
        songRepository.save(lowSelfOpinion);
        Song grip = new Song ("Grip", "4:50", rollinsBand, theEndOfSilence);
        songRepository.save(grip);
        Song tearing = new Song("Tearing", "4:58", rollinsBand, theEndOfSilence);
        songRepository.save(tearing);
        Song youDidntNeed = new Song ("You Didn't Need", "5:30", rollinsBand, theEndOfSilence);
        songRepository.save(youDidntNeed);
        Song almostReal = new Song ("Almost Real", "8:03", rollinsBand, theEndOfSilence);
        songRepository.save(almostReal);
        Song obscene = new Song ("Obscene", "8:50", rollinsBand, theEndOfSilence);
        songRepository.save(obscene);
        Song whatDoYouDo = new Song ("What Do You Do", "7:22", rollinsBand, theEndOfSilence);
        songRepository.save(whatDoYouDo);
        Song bluesJam = new Song("Blues Jam", "11:46", rollinsBand, theEndOfSilence);
        songRepository.save(bluesJam);
        Song anotherLife = new Song("Another Life", "4:39", rollinsBand, theEndOfSilence);
        songRepository.save(anotherLife);
        Song justLikeYou = new Song("Just Like You", "9:30", rollinsBand, theEndOfSilence);
        songRepository.save(justLikeYou);

        Song tooMuchRock = new Song("Too Much Rock and Roll", "3:50", rollinsBand, aNicerShadeOfRed);
        songRepository.save(tooMuchRock);
        Song marcus = new Song("Marcus Has the Evil in Him", "4:01", rollinsBand, aNicerShadeOfRed);
        songRepository.save(marcus);
        Song nowhere = new Song("Nowhere to Go but Inside", "3:04", rollinsBand, aNicerShadeOfRed);
        songRepository.save(nowhere);
        Song tenX = new Song("10X", "3:04", rollinsBand, aNicerShadeOfRed);
        songRepository.save(tenX);
        Song always = new Song("Always the Same", "2:57", rollinsBand, aNicerShadeOfRed);
        songRepository.save(always);
        Song soul = new Song("Soul Implant", "1:56", rollinsBand, aNicerShadeOfRed);
        songRepository.save(soul);
        Song fun = new Song("Ain't It Fun", "3:43", rollinsBand, aNicerShadeOfRed);
        songRepository.save(fun);
        Song lost = new Song("You Lost Me", "5:47", rollinsBand, aNicerShadeOfRed);
        songRepository.save(lost);
        Song stone = new Song("Stone Washed Clean", "4:18", rollinsBand, aNicerShadeOfRed);
        songRepository.save(stone);
        Song lifeDenied = new Song("A Life Denied", "3:25", rollinsBand, aNicerShadeOfRed);
        songRepository.save(lifeDenied);
        Song number = new Song("Your Number IS One (Long Version)", "4:37", rollinsBand, aNicerShadeOfRed);
        songRepository.save(number);
        Song drag = new Song("Such a Drag", "12:55", rollinsBand, aNicerShadeOfRed);
        songRepository.save(drag);

        Song danish = new Song("Danish Pastry Lyrics", "3:32", porridgeRadio, ricePasta);
        songRepository.save(danish);
        Song lemonade = new Song("Lemonade", "2:41", porridgeRadio, ricePasta);
        songRepository.save(lemonade);
        Song barks = new Song("Barks Like A Dog", "5:26", porridgeRadio, ricePasta);
        songRepository.save(barks);
        Song cow = new Song("Walking The Cow (Daniel Johnston cover)", "2:35", porridgeRadio, ricePasta);
        songRepository.save(cow);
        Song hearMe = new Song("Can U Hear Me Now", "7:33", porridgeRadio, ricePasta);
        songRepository.save(hearMe);
        Song sorry = new Song("Sorry", "5:31", porridgeRadio, ricePasta);
        songRepository.save(sorry);
        Song worms = new Song("Worms", "1:51", porridgeRadio, ricePasta);
        songRepository.save(worms);
        Song wasLike = new Song("And I Was Like", "1:38", porridgeRadio, ricePasta);
        songRepository.save(wasLike);
        Song eugh = new Song("Eugh", "4:38", porridgeRadio, ricePasta);
        songRepository.save(eugh);

        Song sweet = new Song("Sweet", "3:42", porridgeRadio, everyBad);
        songRepository.save(sweet);
        Song askMe = new Song("Don't Ask Me Twice", "3:21", porridgeRadio, everyBad);
        songRepository.save(askMe);
        Song giveTake = new Song("Give/Take", "3:53", porridgeRadio, everyBad);
        songRepository.save(giveTake);
        Song lilac = new Song("Lilac", "5:27", porridgeRadio, everyBad);
        songRepository.save(lilac);
        Song circling = new Song("Circling", "3:20", porridgeRadio, everyBad);
        songRepository.save(circling);

        Song tuscan = new Song("Tuscan Leather", "6:06", drake, nothingSame);
        songRepository.save(tuscan);
        Song furthest = new Song("Furthest Things", "4:27", drake, nothingSame);
        songRepository.save(furthest);
        Song bottom = new Song("Started From the Bottom", "2:53", drake, nothingSame);
        songRepository.save(bottom);
        Song wutang = new Song("Wu-Tang Forever", "3:37", drake, nothingSame);
        songRepository.save(wutang);
        Song ownIt = new Song("Own It", "4:11", drake, nothingSame);
        songRepository.save(ownIt);
        Song worst = new Song("Worst Behavior", "4:30", drake, nothingSame);
        songRepository.save(worst);
        Song time = new Song("From Time feat. Jhene Aiko", "5:22", drake, nothingSame);
        songRepository.save(time);
        Song holdOn = new Song("Hold On, We're Going Home feat. Majid Jordan", "3:51", drake, nothingSame);
        songRepository.save(holdOn);
        Song connect = new Song("Connect", "4:56", drake, nothingSame);
        songRepository.save(connect);
        Song language = new Song("The Language", "3:44", drake, nothingSame);
        songRepository.save(language);
        Song city = new Song("305 to My City feat. Detail", "4:15", drake, nothingSame);
        songRepository.save(city);
        Song tooMuch = new Song("Too Much", "4:21", drake, nothingSame);
        songRepository.save(tooMuch);
        Song pound = new Song("Pound Cake/Paris Morton Music feat. Jay-Z", "27:13", drake, nothingSame);
        songRepository.save(pound);

        Song family = new Song("Keep the Family Close", "5:28", drake, views);
        songRepository.save(family);
        Song nine = new Song("9", "4:15", drake, views);
        songRepository.save(nine);
        Song withMe = new Song("U With Me?", "4:57", drake, views);
        songRepository.save(withMe);
        Song feel = new Song("Feel No Ways", "4:00", drake, views);
        songRepository.save(feel);
        Song hype = new Song("Hype", "3:29", drake, views);
        songRepository.save(hype);
        Song weston = new Song("Weston Road Flows", "4:13", drake, views);
        songRepository.save(weston);
        Song redemption = new Song("Redemption", "5:33", drake, views);
        songRepository.save(redemption);
        Song withYou = new Song("With You feat. PartyNextDoor", "3:15", drake, views);
        songRepository.save(withYou);
        Song faithful = new Song("Faithful feat. Pimp C & dvsn", "4:50", drake, views);
        songRepository.save(faithful);
        Song stillHere = new Song("Still Here", "3:09", drake, views);
        songRepository.save(stillHere);
        Song controlla = new Song("Controlla", "4:05", drake, views);
        songRepository.save(controlla);
        Song oneDance = new Song("One Dance feat Wizkid & Kyle", "2:53", drake, views);
        songRepository.save(oneDance);
        Song child = new Song("Child Play", "3:32", drake, views);
        songRepository.save(child);
        Song pop = new Song("Pop Style", "3:32", drake, views);
        songRepository.save(pop);
        Song tooGood = new Song("Too Good feat. Rihanna", "4:23", drake, views);
        songRepository.save(tooGood);
        Song summer = new Song("Summers Over Interlude", "1:46", drake, views);
        songRepository.save(summer);
        Song fire = new Song("Fire & Desire", "3:58", drake, views);
        songRepository.save(fire);
        Song viewsSong = new Song("Views", "5:11", drake, views);
        songRepository.save(viewsSong);
        Song hotline = new Song("Hotline Bling", "4:27", drake, views);
        songRepository.save(hotline);

        Song intro = new Song("Intro", "1:17", slightlyStoopid, closerToSun);
        songRepository.save(intro);
        Song babylon = new Song("Babylon Is Falling", "2:25", slightlyStoopid, closerToSun);
        songRepository.save(babylon);
        Song somebody = new Song("Somebody", "2:52", slightlyStoopid, closerToSun);
        songRepository.save(somebody);
        Song fat = new Song("Fat Spliffs", "3:07", slightlyStoopid, closerToSun);
        songRepository.save(fat);
        Song bandelero = new Song("Bandelero", "2:47", slightlyStoopid, closerToSun);
        songRepository.save(bandelero);
        Song seeIt = new Song("See It No Other Way feat. Barrington Levy & Mr. Mutton", "3:53", slightlyStoopid, closerToSun);
        songRepository.save(seeIt);
        Song nothin = new Song("Nothin Over Me", "1:20", slightlyStoopid, closerToSun);
        songRepository.save(nothin);
        Song joint = new Song("This Joint", "4:07", slightlyStoopid, closerToSun);
        songRepository.save(joint);
        Song older = new Song("Older", "3:39", slightlyStoopid, closerToSun);
        songRepository.save(older);
        Song money = new Song("Aint Got A Lot Of Money", "2:58", slightlyStoopid, closerToSun);
        songRepository.save(money);
        Song wet = new Song("Til It Gets Wet", "2:37", slightlyStoopid, closerToSun);
        songRepository.save(wet);
        Song care = new Song("Don't Care feat. Bill and Prof. Most", "4:39", slightlyStoopid, closerToSun);
        songRepository.save(care);
        Song basher = new Song("Basher", "2:31", slightlyStoopid, closerToSun);
        songRepository.save(basher);
        Song righteous = new Song("Righteous Man", "2:35", slightlyStoopid, closerToSun);
        songRepository.save(righteous);
        Song plane = new Song("Up On A Plane", "3:00", slightlyStoopid, closerToSun);
        songRepository.save(plane);
        Song waiting = new Song("Waiting", "2:55", slightlyStoopid, closerToSun);
        songRepository.save(waiting);
        Song closerToSunSong = new Song("Closer to the Sun", "2:25", slightlyStoopid, closerToSun);
        songRepository.save(closerToSunSong);
        Song zeplike = new Song("Zeplike", "3:34", slightlyStoopid, closerToSun);
        songRepository.save(zeplike);
        Song dome = new Song("Come for My Dome", "1:29", slightlyStoopid, closerToSun);
        songRepository.save(dome);
        Song road = new Song("Open Road", "6:24", slightlyStoopid, closerToSun);
        songRepository.save(road);

        Song everythingNeedSong = new Song("Everything You Need", "3:33", slightlyStoopid, everythingNeed);
        songRepository.save(everythingNeedSong);
        Song officer = new Song("Officer", "3:52", slightlyStoopid, everythingNeed);
        songRepository.save(officer);
        Song questionable = new Song("Questionable", "2:07", slightlyStoopid, everythingNeed);
        songRepository.save(questionable);
        Song runnin = new Song("Runnin With a Gun", "3:31", slightlyStoopid, everythingNeed);
        songRepository.save(runnin;);
        Song killin = new Song("Killin Me Deep Inside", "4:54", slightlyStoopid, everythingNeed);
        songRepository.save(killin);
        Song gentlemen = new Song("Perfect Gentlemen", "1:40", slightlyStoopid, everythingNeed);
        songRepository.save(gentlemen);
        Song wicked = new Song("Wicked Rebel", "4:03", slightlyStoopid, everythingNeed);
        songRepository.save(wicked);
        Song honey = new Song("Sweet Honey", "3:51", slightlyStoopid, everythingNeed);
        songRepository.save(honey);
        Song punkRock = new Song("Punk Rock Billy", "1:38", slightlyStoopid, everythingNeed);
        songRepository.save(punkRock);
        Song worldRound = new Song("World Goes Round", "3:55", slightlyStoopid, everythingNeed);
        songRepository.save(worldRound);
        Song wiseman = new Song("Wiseman", "3:21", slightlyStoopid, everythingNeed);
        songRepository.save(wiseman);
        Song jetPlane = new Song("Leaving on a Jet Plane", "3:16", slightlyStoopid, everythingNeed);
        songRepository.save(jetPlane);
        Song mellow = new Song("Mellow Mood", "4:41", slightlyStoopid, everythingNeed);
        songRepository.save(mellow);
        Song collie = new Song("Collie Man", "2:13", slightlyStoopid, everythingNeed);
        songRepository.save(collie);
    }
}
